name: CI

on: push

jobs:
  deploy:
    needs: test 
    runs-on: ubuntu-latest 
    environment: production 
    steps:
      - uses: actions/checkout@v4
      - name: DepLoy
        env:
          TOKEN: ${f secrets.DEPLOY_TOKEN }}
        run: echo "Deploying to production"







